version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64                # Apple Silicon (M1/M2) kullanıyorsan bırak; Intel isen silebilirsin
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Sa1234!q"            # güçlü parola
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P 'Sa1234!q' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: aspnet-contact-form/Dockerfile
    container_name: aspnet-contact-form
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./aspnet-contact-form/aspnet-contact-form/.env:/app/.env:ro   # .env’yi uygulama içine mount ediyoruz
    ports:
      - "8080:8080"
    restart: always

volumes:
  mssql-data:
